### ISSUE TITLE
Server errors aren't passed through

### ISSUE THREAD

**Issue by Tom4U** [diegomvh/angular-odata#1]
If using the OdataEntityService (in my case the update method) and the server returns an error (in my case 422), the error message from the server is not passed through to the caller, but instead, I always get an error like "scheduler.schedule is not a function".
Update and probably the other HttpClient using methods should pass the correct error as such common error like the mentioned is very hard to debug.

Is it much work to change that?

**Comment by diegomvh** [comment]
Hi Tom, and thanks for given a try to the library and the issue.
Let me try understod the problem... 
All the requests goes throught the HttpClient injected in the ODataService. The `put` method called in updates returns an observable wraped with an error handler.

https://github.com/diegomvh/angular-odata/blob/ca15b25340bb04ea2494d46c1aa4361162ab7e1a/src/lib/odata-service/odata.service.ts#L70

And the wrapping arround the request takes the errors to the custom error function defined in the ODataContext. If the function is defined you can handle the error in here and eventualy throws something more user friendly.

Are you using te `forContext` method on ODataModule import? Like in the [example](https://github.com/diegomvh/angular-odata/blob/master/README.md#usage)

Maybe the implementation is confused and a simple http's interceptor be more acurate for that job, but the library is still under development. Your issue is thomthing than eventualy i must be tested.

Have you tried the code generator for the `$metadata` endpoint?

https://github.com/diegomvh/Od2Ts

Many thanks again for your time.

**Comment by Tom4U** [comment]
Hi Diego,

The code generator is no option in my case as I'm using Generics and Reflection in most cases.
But you brought me onto the right track. I have used the RxJs error handler `throwError` as shown in the documentation I think. I'm pretty sure that's the problem.
I'll check, next time I have an error sent back from my API and will update/close this issue here then.
