### ISSUE TITLE
IEEE754Compatible support

### ISSUE THREAD

**Issue by Bonny88** [diegomvh/angular-odata#12]
Hi Diego,

I'm trying to use sap cds as a backend for an angular app, using your library in order to consume the odata service exposed.

When i try to update or create a new element of my service with a decimal property i get an error from the backend, becouse it requires the decimals in the payload to be encoded as JSON strings, and the content-type header to be "application/json;IEEE754Compatible=true".

I can set the header for the patch operation (but not for the "create") using the httpoptions parameter, but the payload is still not compliant with the specification. Is there a way to handle the conversion (aside from setting the field as a string in the .config of the entity)?

Reference for this error:
https://answers.sap.com/questions/12991667/how-to-format-edmdecimals-in-postputpatch.html

Thanks
Luca

**Comment by diegomvh** [comment]
Hello Luca
A few things come to mind, the first and simplest is to add the options to [create](https://github.com/diegomvh/angular-odata/blob/d8d92652644dd727122914ec31bb0725de16b235/src/lib/services/entity.ts#L63), [update](https://github.com/diegomvh/angular-odata/blob/d8d92652644dd727122914ec31bb0725de16b235/src/lib/services/entity.ts#L68) and [assign](https://github.com/diegomvh/angular-odata/blob/d8d92652644dd727122914ec31bb0725de16b235/src/lib/services/entity.ts#L73) in the entity service... and maybe elsewhere.
On the other hand, similar to what happens with [enums](https://github.com/diegomvh/angular-odata/blob/d8d92652644dd727122914ec31bb0725de16b235/src/lib/models/config.ts#L17), maybe configure the parser for IEEE754 data types and add the header in each request.
I guess that might be the way to go.
Regards
Diego

**Comment by diegomvh** [comment]
How about adding decimal.js as dependency for parser?
https://github.com/MikeMcl/decimal.js

**Comment by diegomvh** [comment]
Hi Luca,
After thinking for a while I think this change handles the issue of `IEEE754Compatible`

A [flag](https://github.com/diegomvh/AngularODataEntity/blob/152dc7845f303a019ba3ea0b8a2c5e5dbd7eb960/src/app/northwind/northwind.config.ts#L13) to indicate that we require compatibility and...
a [parser](https://github.com/diegomvh/AngularODataEntity/blob/152dc7845f303a019ba3ea0b8a2c5e5dbd7eb960/src/app/northwind/northwind.config.ts#L20) that processes input and output from the server if necessary.

Thank you for reporting the issue and I hope this helps.
Let me know if it turned out as you expected.

Regards
