### ISSUE TITLE
How can I pass 'withCount' parameter when I choose function API ?

### ISSUE THREAD

**Issue by Coder7777** [diegomvh/angular-odata#31]
```TypeScript
 return this._customersOdata
      .filter(filter)
      .top(top)
      .skip(skip)
      .get({ withCount: true }).pipe(map((result) => {
        return { data: result.entities, count: result.annots.count };
      }));
```

I can get the total count per search from the above code.

But when I use the function API, how could I get the total count as follow

```TypeScript
 return this._customersOdata
      .top(top)
      .skip(skip)
      .select(selectOpts) 
      .function<{ PhoneNumber: string }, Customer>('GetCustomersByPhone')
      .callEntities({ PhoneNumber: phoneNumber })
      .pipe(map(result => result));
```

**Comment by diegomvh** [comment]
Hi @Coder7777 
Every `call<thing>` in functions and actions map the result to the thing that you call.
In order to retrieve the data and de annotations, after read your issue, i see that is not so simple get this two values from the current API.

You would have to construct the invocation to get passing the parameters as follows, https://github.com/diegomvh/angular-odata/blob/682f9dce54a820b647f70f7520a93c6d7b254b13/projects/angular-odata/src/lib/resources/types/function.ts#L179
...and don't pipe the output.

I think it requires a bit of maturing the issue of when and under what type of calls to make the strip of the annotations

Regards

**Comment by diegomvh** [comment]
In 5bd567 i add skip top, etc to function resource.... Now You can do

```TypeScript
 return this._customersOdata
      .function<{ PhoneNumber: string }, Customer>('GetCustomersByPhone')
      .parameters({ PhoneNumber: phoneNumber })
      .top(top)
      .skip(skip)
      .select(selectOpts) 
      .get({withCount: true, responseType: 'entities'});
```

**Comment by Coder7777** [comment]
> In [5bd56e7](https://github.com/diegomvh/angular-odata/commit/5bd56e75ab5f83cb37df1213c986d022d50ad5c8) i add skip, top, etc. to function resource.... Now you can do
> 
> ```ts
>  return this._customersOdata
>       .function<{ PhoneNumber: string }, Customer>('GetCustomersByPhone')
>       .parameters({ PhoneNumber: phoneNumber })
>       .top(top)
>       .skip(skip)
>       .select(selectOpts) 
>       .get({withCount: true, responseType: 'entities'});
> ```

Thanks a lot. Hope the documentation could cover as much API as possible.
