### ISSUE TITLE
C(R)UD Examples

### ISSUE THREAD

**Issue by krstev1994** [diegomvh/angular-odata#35]
Hi Diego,
Can you provide some examples of using create, update and destroy methods?
Get and fetch options are well documented!
Thanks and BR,
Vasil.

**Comment by diegomvh** [comment]
Hi @krstev1994 

I am working in the services these days. According to your comment in issue #27 and the true lack of documentation :)
Prepare an example of CRUD in: 
https://github.com/diegomvh/AngularODataEntity/blob/0aa8fb9aa7a2865c176cd4a76fb650fed361a129/src/app/app.component.ts#L197

This example is for the new version, because based on issue #34 I saw that the services needed to be refactored.

In version 0.65.0 I release the changes.

Regards

**Comment by diegomvh** [comment]
CRUD Example:

https://github.com/diegomvh/AngularODataEntity/blob/c587ff675b0ee02fdb7295d57bdcaac87e640353/src/app/app.component.ts#L197
