### ISSUE TITLE
Writing Binaries

### ISSUE THREAD

**Issue by sandersdevelopment** [diegomvh/angular-odata#36]
Hello again 👍 

We can retrieve Binaries for any given resource like this: 
` return this.client.entitySet<Object>(ENDPOINT).entity(Object.Id).value().fetchBlob().pipe(....)`

But is there any equivalent solution for posting binaries? I expected some sort of .entity(Object.Id).value().postBlob() but can't find anything. Maybe you can help? 

Thanks 💯 !

**Comment by diegomvh** [comment]
Hi @sandersdevelopment 

can you provide some data about de odata standars for posting blobs?, i google'ling for some of that

About your issue, you can allweys use the client with the full http primitives maped to the http client of angular but using resources.

```typescript
const formData = new FormData();
formData.append("file", file);
const resource = this.client.entitySet<Object>(ENDPOINT).entity(Object.Id).value();
this.client.post(resource, formData);
```

The resource API tries to map the details of the standard, of course I will try to contemplate the possibility of posting data from the `value` resource. But at the moment, don't look too much on the internet about how the standard says what to do.

Thanks to you guys for posting the issue and taking the time to test the library.

**Comment by sandersdevelopment** [comment]
Thanks for your fast reply!

I can't find much about the odata standard itself regarding positing binaries, but in another projekt, we used the simple.odata.client in C# where they set a media stream like this: 

https://github.com/simple-odata-client/Simple.OData.Client/blob/master/src/Simple.OData.Client.IntegrationTests/TripPinTests.cs#L1259

We have another self hosted odata api where we take the .Media().setStreamAsync() and interpret it like this: 

![serversideBinaryUpload](https://user-images.githubusercontent.com/54041816/125278748-66972f80-e313-11eb-88d8-ef14adf12dde.png)

Since this works with the simple.odata.client I believe the standard says PUT on the $value endpoint

I will give your solution a try in a moment :-) 

Btw: Is there any way to donate for this project? Since we think about using it in production, we'd love to do that.

Thanks :-)

**Comment by diegomvh** [comment]
Hi
Thank you for providing information to see the topic of the media.
One idea is to go back to the implementation of the media resource that the library had at some point, this would be:

```typescript
# For Entity
this.client.entitySet<Object>(ENDPOINT).entity(Object.Id).media().fetchBlob().pipe(....)
# For Navigation
this.client.entitySet<Object>(ENDPOINT).entity(Object.Id).navigationProperty<Property>("Property").media().fetchBlob().pipe(....)
```
Unfortunately I find it difficult to find more information on the internet about how to implement the `PUT` and that it conforms to the standard, I don't quite understand if it is the correct way and how the implementation of server to receive the request.

I'm going to try something this way: "...we use PUT instead of POST) works, when we push the blob without any form data but with the application/octet-stream header!"

Could you please provide me with the call code using the client? Was it just writing the blob with the "application/octet-stream" header?
To start I see to create the media resource, I hope you can help me with the tests, I do not have the reception of streams implemented in my backend.

Thank you very much and I hope my request is not annoying.
